# Generated by Django 4.2 on 2023-12-05 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('breed', models.CharField(max_length=50, verbose_name='Порода')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('photo', models.ImageField(upload_to='cats', verbose_name='Изображение')),
                ('health_status', models.CharField(max_length=50, verbose_name='Состояние здоровья')),
                ('gender', models.CharField(max_length=50, verbose_name='Пол')),
                ('sterilization', models.CharField(max_length=50, verbose_name='Стерилизация')),
                ('date', models.DateField(verbose_name='Дата рождения')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Диагноз')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Кошка',
                'verbose_name_plural': 'Кошки',
            },
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cats.cat', verbose_name='Кошка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Усыновитель')),
            ],
            options={
                'verbose_name': 'Заявление об усыновлении',
                'verbose_name_plural': 'Заявления об усыновлении',
            },
        ),
    ]
