# Generated by Django 4.2 on 2023-12-05 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='date',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='cat_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
        migrations.AddField(
            model_name='cat',
            name='address',
            field=models.CharField(default='Улица Пушкина дом Колотушкина', max_length=255, verbose_name='Найден(а) по адресу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='color',
            field=models.CharField(default='Белый', max_length=50, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='receipt_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата поступления'),
            preserve_default=False,
        ),
    ]
